AWSTemplateFormatVersion: 2010-09-09
Description: Creates a VPC with public and private subnets
Resources:
  VPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 192.168.101.0/24
  PublicSubnetA: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-west-2a" 
      CidrBlock: 192.168.101.0/28
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
  PrivateSubnetB: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-west-2c"
      CidrBlock: 192.168.101.32/28
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
  SecGr:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "ginsec"
      GroupDescription: "allow ssh and http"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  
  inst:  
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
        - Key: name
          Value: gehaninst
      ImageId: ami-09ee0944866c73f62
      InstanceType: t2.micro
      KeyName: abdo-london
      SecurityGroupIds: 
       - !Ref SecGr
      SubnetId: !Ref PublicSubnetA
